<?php
/**
 * @var ABSoft_StoreListing_Block_Index $this
 */
?>

<div class="container-fuild container-first">
    <div class="row">
        <div class="col-md-12">
            <div class="content-background">
                <div class="content-page">
                    <div class="page-title">
                        <h1 class="title">
                            <span>KENGKENG</span>
                        </h1>
                    </div>
                    <div class="page-control">
                        <div class="panel-control">
                            <div class="title-form">
                                Deine Straße, Hausnummer & PLZ
                            </div>
                            <div class="content-form">
                                <form id="person-form-validate" class="form-inline" method="get"
                                      action="<?php echo $this->getActionOfForm() ?>">
                                    <input type="text" placeholder="Pizzastraße 1, 10117, Berlin"
                                           class="form-control required-entry input-search" value="" name="search"
                                           id="search-input" autocomplete="off">
                                    <input type="hidden" name="lng" id="lng">
                                    <input type="hidden" name="lat" id="lat">
                                    <input type="submit" class="btn btn-success btn-search"
                                           value="<?php echo $this->__('Search') ?>">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="container-fuild container-second">
    <div class="row">
        <div class="col-md-12">
            <div class="content-second">
                <div class="list-item">
                    <div class="item-1 item">
                        <div class="item-img">
                            <img src="/media/item1.png" alt="">
                        </div>
                        <div class="item-number"><span>1</span></div>
                        <div class="item-text"><h4>SUCH DIR WAS AUS</h4></div>
                    </div>
                    <div class="item-2 item">
                        <div class="item-img">
                            <img src="/media/item2.png" alt="">
                        </div>
                        <div class="item-number"><span>2</span></div>
                        <div class="item-text"><h4>BESTELL'S DIR</h4></div>
                    </div>
                    <div class="item-3 item">
                        <div class="item-img">
                            <img src="/media/item3.png" alt="">
                        </div>
                        <div class="item-number"><span>3</span></div>
                        <div class="item-text"><h4>SCHON UNTERWEGS!</h4></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fuild container-third">
    <div class="row">
        <div class="col-md-12">
            <div class="content-third">
                <div class="list-item">
                    <div class="item-1 item">
                        <div class="item-img"><img src="/media/deals.png" alt=""></div>
                        <div class="item-info"><b>KENGKENG.DE DEALS</b></div>
                        <div class="item-content">
                            <div class="item-content-text"><span>Du kannst auf pizza.de täglich mit mehr als 1.000 Deals richtig sparen, also bestell Pizza, Burger, Sushi und Asiatisch so günstig wie nie. Finde gleich den besten Deal in deiner Stadt!</span></div>
                            <div class="item-content-link"><a href="#">Mehr...</a></div>
                        </div>
                    </div>
                    <div class="item-1 item">
                        <div class="item-img"><img src="/media/apps.png" alt=""></div>
                        <div class="item-info"><b>APPS & MOBILE</b></div>
                        <div class="item-content">
                            <div class="item-content-text"><span>Bestell doch mal Essen bei einem Lieferservice mit der pizza.de App für iPhone, iPad, Android und Windows Phone oder über die mobile Website.</span></div>
                            <div class="item-content-link"><a href="#">Mehr...</a></div>
                        </div>
                    </div>
                    <div class="item-1 item">
                        <div class="item-img"><img src="/media/livetracking.png" alt=""></div>
                        <div class="item-info"><b>KENGKENG.DE LIVETRACKING</b></div>
                        <div class="item-content">
                            <div class="item-content-text"><span>Mit dem LiveTracking von pizza.de kannst du die Lieferung des Lieferdiensts in Echtzeit auf der Karte mitverfolgen.</span></div>
                            <div class="item-content-link"><a href="#">Mehr...</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>