<?php
//lấy danh sách các store từ block để hiển thị
?>
<!--<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">-->
<!--    <div class="form-group">-->
<!--        <label for="" class="col-sm-2 control-label"></label>-->
<!--        <div class="col-sm-6">-->
<!--            <select class="form-control" id="">-->
<!--                <option value="distance">--><?php //echo $this->__('Distance') ?><!--</option>-->
<!--                <option value="best">--><?php //echo $this->__('Best') ?><!--</option>-->
<!--                <option value="lowest">--><?php //echo $this->__('Lowest - Highest') ?><!--</option>-->
<!--                <option value="highest">--><?php //echo $this->__('Highest - Lowest') ?><!--</option>-->
<!--            </select>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <select name="name" id="sort" class="form-control">
            <option value="distance">Distance</option>
            <option value="rating">Rating</option>
            <option value="lowest">Lowest price</option>
            <option value="highest">Highest price</option>
        </select>

    </div>
</div>
<div id="list-store">
<?php echo $this->getChildHtml('storelisting.index.list.store') ?>
</div>
<!--<div id="list">-->
<!--</div>-->
<div class="modal" id="modal-review" style="display: none">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3><?php $this->__("Review Store") ?></h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>
<div class="loadding-img" style="display: none;">
    <img src="/media/storelisting/Loading_icon.gif" alt="">
</div>


<script>
    (function($){
//        var url = window.location.href;
//        url = url.split('&sort=')[1];
//        $('#sort').val(url);
//        $(document).on('ready',function(){

//            $('#sort').change(function(){
//
//                var url = window.location.href;
//                url = url.split('&sort')[0];
//                url = url+'&sort='+this.value;
//                location.href = url;
//            })
        $('#sort').change(function() {
            var value = this.value;
            if(value ==='distance'){

                distance()
            }
            if(value ==='rating'){


                rating()
            }
            if(value ==='lowest'){
                lowest()
            }
            if(value ==='highest'){

                highest()
            }
        })
        function distance (){
            console.log("distance")

            $('#list-store .restaurant').sort(function(a,b){
                console.log(a.dataset.distance)

                return a.dataset.distance > b.dataset.distance
            }).appendTo('#list-store')
        }
        function rating(){
            console.log("rating")
            $('#list-store .restaurant').sort(function(a,b){
                console.log(a.dataset.rating)
                return a.dataset.rating > b.dataset.rating
            }).appendTo('#list-store')
        }
        function lowest(){
            console.log("lowest")

            $('#list-store .restaurant').sort(function(a,b){
                console.log(a.dataset.lowest)

                return a.dataset.lowest > b.dataset.lowest
            }).appendTo('#list-store')
        }
        function highest(){
            console.log("highest")

            $('#list-store .restaurant').sort(function(a,b){
                console.log(a.dataset.highest)

                return a.dataset.highest > b.dataset.highest
            }).appendTo('#list-store')
        }
//        })
    })(jQuery);
</script>