<?php
/**
 * Project name 05.Development
 * Created by:
 * User: Hoang Van Cong
 * Company: Theappnow.com
 * Email: conghv@theappnow.com
 * Date: 3/1/2017
 * Time: 10:35 AM
 */

function _getNodeHtml($category, $value=null){
    if (!$category instanceof Mage_Catalog_Model_Category) return '';

    $html = sprintf('<option value="%s" %s>', $category->getId(), $category->getId() == $value ? 'selected="selected"' : '');
    $html .= str_repeat('&nbsp;',  4 * ($category->getLevel()-2) ) . ' - ' . $category->getName();
    $html .= '</option>';

    if ($category->hasChildren()){
        foreach ($category->getChildrenCategories() as $child){
            $html .= _getNodeHtml($child, $value);
        }
    }

    return $html;
}
$collection = Mage::getModel('catalog/category')->getCollection()
    ->addAttributeToSelect('name')
    ->addFieldToFilter('parent_id', array('eq' => 2));

$html .= '<select style="height:200px;" multiple name="category[]" id="categories" class="input-text required-entry"';
$root_category_id =  Mage::app()->getStore()->getRootCategoryId();
$categoryModels = Mage::getModel('catalog/category')->getCollection()
    ->addAttributeToSelect('entity_id')
    ->addAttributeToSelect('name')
    ->addAttributeToFilter('parent_id',2)
    ->addAttributeToFilter('level',2)
    ->addAttributeToFilter('is_active', 1)
    ->addAttributeToSelect("name")
    ->addAttributeToSelect("description")
    ->addAttributeToSelect('thumbnail');
$categorys=[];
foreach ($categoryModels as $item) {
    array_push($categorys,$item->getData());
}
//echo json_encode($categorys);
//die;
//var_dump($categorys);


$html .= '>';
$html .= '<option value="">'.$this->__('Please Select Categories').'</option>';

foreach ($collection as $item) {
    $html .= _getNodeHtml($item, $select);
}

$html .= '</select>';
?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.17.1/axios.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<div class="columns" id="app">
    <div id="page:left" class="side-col">
        <h3>Import Products</h3>
        <ul class="tabs" id="slide_tabs">
            <li>
                <a class="tab-item-link active" title="Item Information" name="form_section"
                   id="slide_tabs_form_section" href="#">
                    <span><span title="The information in this tab has been changed." class="changed"></span><span
                                title="This tab contains invalid data. Please solve the problem before saving."
                                class="error"></span>Item Information</span>
                </a>

            </li>
        </ul>

    </div>
    <div id="content" class="main-col">
        <div class="main-col-inner">
            <div id="messages"></div>
            <div class="content-header">
                <h3 class="icon-head head-adminhtml-slide">Import Products</h3>
            </div>
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend">Form import</h4>

                    <div class="form-buttons"></div>
                </div>
                <div class="fieldset">


                    <!-- demo root element -->
                    <div id="demo">
                        <form @submit="submit" target="_blank" id="form-upload-product" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl('admin_import/adminhtml_import/updateProduct')?>">
                            <table cellspacing="0" class="form-list" id="upload-image">
                                <tbody>
                                <tr>
                                    <td class="label">
                                        <label>Import type</label>
                                    </td>
                                    <td class="value">
                                        <input checked type="radio" name="importType" value="create" id="create-update-product"/>
                                        <label for="create-update-product">Create & update exists</label>
                                        <input  type="radio" name="importType" value="update" id="update-product"/>
                                        <label for="update-product">Update exists only</label>
                                        <input  type="radio" name="importType" value="xcreate" id="create-product"/>
                                        <label for="create-product">Create new only</label>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label">
                                        <label>Special feature</label>
                                    </td>
                                    <td class="value">
                                        <input checked type="checkbox" name="createConfigurable" value="1" id="create-configurable"/>
                                        <label for="create-configurable">Create configurable product</label>
                                        <input checked type="checkbox" name="createTierprice" value="1" id="create-tierprice"/>
                                        <label for="create-tierprice">Create tierprice</label>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label">
                                        <label>Price</label>
                                    </td>
                                    <td class="value">
                                        <input checked type="radio" name="priceType" value="insert" id="include-tax"/>
                                        <label for="include-tax">Include Tax</label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                        <input  type="radio" name="priceType" value="update" id="exclude-tax"/>
                                        <label for="exclude-tax">Exclude Tax</label>
                                    </td>
                                </tr>
                                <!--  <tr>
                                <td class="label">
                                    <label>Select Categories</label>
                                </td>
                                <td class="value">
                                    <?php //echo $html; ?>
                                </td>
                            </tr> -->
                                <tr >
                                    <td class="label">
                                        <label>Upload your images</label>
                                    </td>
<!--                                    #########-->
                                    <td class="value">
                                        <input id="images" class="input-file" type="file" @change="initData" multiple="multiple"/>
                                        <p><strong>Note: </strong><i>Just accept *.jpg,*.png file.</i></p>
                                        <p> <button @click="upload()" type="button" >Upload</button> </p>
                                        <span id="loading-data-upload" style="display: none">
                                            <img width="30" src="<?php echo $this->getSkinUrl('images') . '/ajax-loader.gif' ?>"/>
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label">
                                        <input name="form_key" type="hidden" id="formkey"
                                               value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>
                                        <input type="hidden" id="file_data" value=""/>
                                        <label>Select a File</label>
                                    </td>
                                    <td class="value">
<!--                                        <input onchange="getDataFile();" class="input-file" type="file" name="productfeed"/>-->
                                        <input @change="getDataFile" class="input-file" type="file" name="productfeed"/>
                                        <p><strong>Note: </strong><i>Just accept csv file.</i></p>
                                        <span class="loading-data" v-show="isLoad">
                                            <img width="30" src="<?php echo $this->getSkinUrl('images') . '/ajax-loader.gif' ?>"/>
                                        </span>
                                    </td>
                                </tr>
                                <tr id="fields-mapping"  v-show="isShow">
                                    <td class="label">
                                        Fields mapping
                                    </td>
                                    <td>
                                     <table class="table-mapping" id="table-mapping" >
                                          <tr>
                                              <th>Fields in csv file<br/>(first row)</th>
                                                <th>Product\'s Attribute</th>
                                         </tr>
                                         <tr v-for="(row,index) in csv_data" :key="index">
                                             <input v-if="row=='sku'" name="skuColumnIdx" :value="index" type="hidden" />

                                             <td>{{row}}</td>
                                             <td>
                                                 <select :name="'mapFields['+index+']'">
                                                     <option value="">- Select one Attribute __</option>
                                                     <option v-for="field in fields" :value="field" :selected="row==field">{{field}}</option>
                                                 </select>
                                             </td>
                                         </tr>
                                         </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td class="value">
                                        <button   :type="hasCsv?'submit':'button'"  class="button" @click="alert">
                                            <span><span>{{hasCsv?'Import':'Pls Import a CSV'}}</span></span></button>
                                        <span class="loading-data" v-show="isLoad">
                                            <img width="30" src="<?php echo $this->getSkinUrl('images') . '/ajax-loader.gif' ?>"/>
                                        </span>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </form>



                    </div>


                </div>
            </div>
            <div class="loading-data" style="display: none">
                <img src="<?php echo $this->getSkinUrl('images') . '/ajax-loader.gif' ?>"/>
            </div>
        </div>
    </div>
</div>

<script>
    var formkey = document.getElementById('formkey').value;
    var url = '<?php echo $this->getUrl('import/adminhtml_import/upload/')?>form_key/' + formkey
    var app =  new Vue({
        el:'#upload-image',
        data:{
            images:new FormData(),
            csv_data:[],
            fields:[],
            isShow:false,
            isLoad:false,
            hasCsv:false
        },
        methods:{
            upload(){
                var img_loading = document.getElementById('loading-data-upload');
                img_loading.style.display = 'block';
                axios.post(url,this.images,{
                    headers: {
                        'Content-Type': 'multipart/form-data'
                    }
                }).then(function(response){
                    img_loading.style.display = 'none';
                    alert("upload success !")
                })
            },
            initData(event){
                for(let key in event.target.files){
                    this.images.append('images[]',event.target.files[key])
                }
            },
            getDataFile(event){

                var csv = event.target.files[0];
                var formData =  new  FormData();
                formData.append('productfeed',csv);
                var url = '<?php echo $this->getUrl('import/adminhtml_import/getdatafile/')?>form_key/' + formkey;
                var app = this;
                axios.post(url,formData,{
                    headers: {
                        'Content-Type': 'multipart/form-data'
                    }
                }).then(function(response){
                    app.isLoad =true;
                    if(response.data===0){
                        alert("Invalid file.")
                    } else {
                        app.csv_data = response.data.maps;
                        app.fields = response.data.fields;
                        app.isShow = true;
                        app.hasCsv = true;
                        app.isLoad =false;
                    }
                })
            },
            submit(event){
                event.preventDefault();

                console.log("submti")
                if(this.hasCsv===false){
                    alert('Please Select a file import!')
                }
            },
            alert(){
                if(this.hasCsv===false){
                    alert('pls import file csv')
                }
            }
        }

    })
</script>

<script type="text/javascript">

    function getDataFile() {
        var fd = new FormData(document.getElementById("form-upload-product"));
        var formkey = document.getElementById('formkey').value;

//        axios.post(
//            '<?php //echo $this->getUrl('import/adminhtml_import/getdatafile/')?>//form_key/' + formkey,
//            fd,
//            {
//                headers: {
//                    'Content-Type': 'multipart/form-data'
//                }
//            }
//        )
//            .then(function(data){
//                document.getElementById('file_data').value = 1;
//                document.getElementById('fields-mapping').style.display = 'block';
//                document.getElementById('mapping').innerHTML= data.data.mapFields
//
//            });
        jQuery.ajax({
            url: '<?php echo $this->getUrl('import/adminhtml_import/getdatafile/')?>form_key/' + formkey,
            type: "POST",
            data: fd,
            dataType: 'json',
            enctype: 'multipart/form-data',
            processData: false,  // tell jQuery not to process the data
            contentType: false,   // tell jQuery not to set contentType
            beforeSend: function () {
                jQuery('span.loading-data').show();
            },
            success: function (data) {
                jQuery('span.loading-data').hide();
                if (data == '0') {
                    alert('Invalid file.');
                } else {
                    jQuery('#file_data').val(1);
                    jQuery('#fields-mapping').show();
                    jQuery('#mapping').html(data.mapFields);
                }
            }
        });
    }
    function onImportProduct() {
        var product = jQuery('#file_data').val();
        if (product != '') {
            var form = jQuery('#form-upload-product');
            form.submit();
            //reindexData();

        } else {
            alert('Please Select a file import!');
        }

        return false;
    }

    function pushData(k, datafile) {
        jQuery.ajax({
            url: '<?php echo $this->getUrl('trophydata/import/importProduct')?>',
            type: "POST",
            async: false,
            timeout: 20000,
            data: {
                form_key: jQuery('#formkey').val(),
                name: datafile[0],
                short_description: datafile[1],
                sku: datafile[5],
                price: datafile[7],
                categories: datafile[14],
                trophysize: datafile[17],
                images: datafile[13]
            },
            dataType: 'json',
            beforeSend: function () {
                jQuery('.loading-data').show();
            },
            success: function (data) {
                jQuery('.loading-data').hide();
                if (data.name) {
                    var row = '<tr>';
                    row += '<td>' + k + '</td>';
                    row += '<td><img alt="" src="' + data.image + '" width="50"/></td>';
                    row += '<td>' + data.sku + '</td>';
                    row += '<td>' + data.name + '</td>';
                    row += '</tr>';
                    jQuery('#table-content-upload').append(row);
                }
            }

        });
        jQuery('.loading-data').hide();
    }

    function reindexData() {
        jQuery.ajax({
            url: '<?php echo $this->getUrl('trophydata/import/reindex')?>',
            type: "GET",
            async: false,

            dataType: 'json',
            beforeSend: function () {
                jQuery('.loading-data').show();
            },
            success: function (data) {
                jQuery('.loading-data').hide();

            }
        });
    }
</script>

<style type="text/css">
    .data-import table {
        border-collapse: collapse;
    }

    .data-import table td, .data-import table th {
        border: 1px solid #d0def0;
    }

    .data-import table td {
        padding: 5px;
    }
    .table-mapping {border: 1px solid #d0cbc1; border-collapse: collapse;}
    .table-mapping td{
        padding: 5px 10px;
    }
    .table-mapping th{
        padding: 10px;
        border: 1px solid #d0cbc1;
    }
</style>