<?php
/**
 * @var ABSoft_StoreListing_Block_List $this
 */
$data = $this->getStoreByCode();
$store = $data[0];
$google_map_key = Mage::getStoreConfig('store_location/general/google_key',Mage::app()->getStore());

?>
<div class="right-restaurant-info">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 right-restaurant-info_detail">
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 right-restaurant-info_img">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'storelisting/' . $store['img'] ?>"
                 alt="">
        </div>
        <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
            <h3><?php echo $store['namestore'] ?></h3>
            <p>
            <div class="rating-box">
                <div class="rating"
                     style="width: <?php echo $this->getRatingSummaryStore($store['store_id']) ?>%"></div>
            </div>
            <div class="count-review" data-store-id="<?php echo $store['store_id'] ?>"
                 style="cursor: pointer">
                (<?php echo $this->getCountReview($store['store_id']) ?>)
            </div>
            </p>
            <p><i class="fa fa-map-marker" aria-hidden="true"></i> <?php echo $store['address'] ?></p>
            <p><i class="fa fa-clock-o" aria-hidden="true"></i> <?php echo str_replace(',',':',$store['time_open']).' - '.str_replace(',',':',$store['time_close'])?></p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'storelisting/payment.png' ?>" alt="">
        </div>
    </div>
    
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="padding:0px">
            <div id="map"></div>
        </div>
    
</div>
<style>
    #map {
        width: 100%;
        height: 260px;
    }
</style>
<div class="clearfix">
</div>
<div class="modal" id="modal-review" style="display: none">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Review Store</h3>
    </div>
    <div class="modal-body">

    </div>
    <div class="modal-footer">
    </div>
</div>

<script>
      function initMap() {
        var uluru = {lat: <?php echo $store['latitude'] ?>, lng:<?php echo $store['longitude'] ?>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 10,
          center: uluru
        });
          var marker = new google.maps.Marker({
              position: uluru,
              map: map
          });
      }

    </script>
<script src="https://maps.googleapis.com/maps/api/js?key=<?php echo $google_map_key?>&libraries=places&callback=initMap" async defer></script>