<?php
/**
 * @var ABSoft_StoreListing_Block_List $this
 */
$data = $this->getStoreByCode();
$store = $data[0];
?>
<div class="right-restaurant-info">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 right-restaurant-info_detail">
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 right-restaurant-info_img">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'storelisting/' . $store['img'] ?>"
                 alt="">
        </div>
        <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
            <h3><?php echo $store['namestore'] ?></h3>
            <p>
            <div class="rating-box">
                <div class="rating"
                     style="width: <?php echo $this->getRatingSummaryStore($store['store_id']) ?>%"></div>
            </div>
            <div class="count-review" data-store-id="<?php echo $store['store_id'] ?>"
                 style="cursor: pointer">
                (<?php echo $this->getCountReview($store['store_id']) ?>)
            </div>
            </p>
            <p><i class="fa fa-map-marker" aria-hidden="true"></i> <?php echo $store['address'] ?></p>
            <p><i class="fa fa-clock-o" aria-hidden="true"></i> <?php echo $store['time_open'] ?></p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'storelisting/payment.png' ?>" alt="">
        </div>
    </div>
</div>

<div class="clearfix">
</div>
<div class="modal" id="modal-review" style="display: none">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Review Store</h3>
    </div>
    <div class="modal-body">

    </div>
    <div class="modal-footer">
    </div>
</div>