<?php
/**
 * Created by PhpStorm.
 * User: Truong Tuan Dat
 * Date: 9/14/2017
 * Time: 9:53 AM
 */
?>
<style>
    .show-store {
        left: 0px !important;

    }

    .hidden-store {
        left: -200px !important;
    }

    #choose-store {
        cursor: pointer;
        position: fixed;
        display: flex;
        top: 260px;
        left: 0px;

    }

    .form-choose-package {
        position: absolute;
        /* position: fixed !important; */
        left: -104px;
        top: 104px;
        transform: rotate(-90deg);
        z-index: 20;
        width: 239px;
    }

    .form-choose-package .show-label {
        background: #e4027c;
        color: #fff;
        font-size: 21px;
        text-transform: uppercase;
        border-radius: 0 0 0 5px;
        padding: 5px 30px;
        position: relative;
    }

    .form-choose-package .show-label .label {
        color: #fff;
    }

    .form-choose-package .show-label .show {
        position: absolute;
        right: 0px;
        bottom: -25px;
        background: #e4027c;
        font-size: 18px;
        transform: rotate(90deg);
        padding: 0px 4px;
        border-radius: 0 3px 3px 0;
        cursor: pointer;
    }

    .form-choose-package .show-label .redcolor {
        font-weight: bold;
        color: #cc0000;
    }

    .container-store {
        position: fixed;
        padding: 5px;
        height: auto;
        background: #e4027c;
        /* position: fixed !important; */
        left: 0px;
        /* top: 38%; */
        z-index: 20;
        width: 180px;
        box-sizing: border-box;
        -webkit-transition: width 0.5s; /* Safari */
        transition: left 0.3s linear;
    }

    #choose-store .logo {
        width: 160px;
        height: 112px;
        float: left;
        background: white;
        line-height: 112px;
    }

    #choose-store .logo img {
        max-width: 100%;
        max-height: 100%;
        vertical-align: middle;
    }

    #choose-store .row-store {
        width: 100%;
        height: auto;
        clear: both;
    }

    #choose-store .row-store:first-child {
        margin-bottom: 5px;

    }

    #choose-store .name-store {
        margin-top: 5px;
        float: left;
        color: white;

    }

    #choose-store .close-button {
        width: 15px;
        height: 15px;
        background: black;
        color: white;
        z-index: 1000;
        position: absolute;
        left: 172px;
        top: -5px;
        border-radius: 10px;

    }

    .clearfix:after {
        clear: both;
        content: ".";
        display: block;
        width: 0px;
        height: 0px;
    }
</style>
<div id="choose-store" class="">
    <div class="form-choose-package form-choose-package1">
        <div class="show-label">
            <div class="label"> Choose Store</div>
        </div>
    </div>
    <div class="container-store hidden-store">
        <?php
        foreach (Mage::app()->getWebsites() as $website) {
            foreach ($website->getGroups() as $group) {
                $stores = $group->getStores();
                foreach ($stores as $store) { ?>
                    <div class="row-store clearfix">
                        <a href="/?___store=<?php echo $store->getCode() ?>">

                            <div class="logo"><img src="/media/choosestore/<?php echo $store->getCode() ?>.png" alt="">
                            </div>
                            <!--                        <div class="name-store">-->
                            <?php //echo $group->getName()?><!--</div>-->
                        </a>
                    </div>
                    <?php break;
                }
            }
        }
        ?>
        <div class="close-button">X</div>

    </div>
</div>
<script>
    //    (function($){
    //        $(".form-choose-package").click(function(){
    //            $("#choose-store").toggleClass("show-store hidden-store");
    //        })
    //        $(".close-button").click(function(){
    //            $("#choose-store").toggleClass("show-store hidden-store");
    //        })
    //    })(jQuery);
    (function ($) {
        $(".form-choose-package").click(function () {
            $(".container-store").toggleClass("show-store hidden-store");
        })
        $(".close-button").click(function () {
            $(".container-store").toggleClass("show-store hidden-store");
        })
    })(jQuery);

</script>

