<?php
/**
 * @var ABSoft_StoreListing_Block_Index $this
 */
?>

<div class="container-fuild">
    <div class="container container-1">
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <div class="page-title">
                    <h1 class="title">
                        <span>KENGKENG</span>
                    </h1>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">

                </div>
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                    <div class="page-control">
                        <div class="panel-control">
                            <div class="title-form">
                                Deine Straße, Hausnummer & PLZ
                            </div>
                            <div class="content-form">
                                <form id="person-form-validate" class="form-inline" method="get"
                                      action="<?php echo $this->getActionOfForm() ?>">
                                    <input type="text" placeholder="Pizzastraße 1, 10117, Berlin"
                                           class="form-control required-entry input-search" value="" name="search"
                                           id="search-input" autocomplete="off">
                                    <input type="hidden" name="lng" id="lng">
                                    <input type="hidden" name="lat" id="lat">
                                    <input type="submit" class="btn btn-success btn-search"
                                           value="<?php echo $this->__('Search') ?>">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">

                </div>
            </div>
        </div>
    </div>
</div>
<div class="container container-2">
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="content-2 content">
                <div class="list-item">
                    <div class="item-1 item col-md-4 col-xs-12">
                        <div class="item-img">
                            <img src="/media/item1.png" alt="">
                        </div>
                        <div class="item-number"><span>1</span></div>
                        <div class="item-text"><h4>SUCH DIR WAS AUS</h4></div>
                    </div>
                    <div class="item-2 item col-md-4 col-xs-12">
                        <div class="item-img">
                            <img src="/media/item2.png" alt="">
                        </div>
                        <div class="item-number"><span>2</span></div>
                        <div class="item-text"><h4>BESTELL'S DIR</h4></div>
                    </div>
                    <div class="item-3 item col-md-4 col-xs-12">
                        <div class="item-img">
                            <img src="/media/item3.png" alt="">
                        </div>
                        <div class="item-number"><span>3</span></div>
                        <div class="item-text"><h4>SCHON UNTERWEGS!</h4></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container container-3">
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="content-3 content">
                <div class="list-item">
                    <div class="col-md-4 col-xs-12 text-center">
                        <div class="item-img"><img src="/media/deals.png" alt=""></div>
                        <div class="item-info"><b>KENGKENG.DE DEALS</b></div>
                        <div class="item-content text-left">
                            <div class="item-content-text"><span>Du kannst auf kengkeng.de täglich mit mehr als 1.000 Deals richtig sparen, also bestell Pizza, Burger, Sushi und Asiatisch so günstig wie nie. Finde gleich den besten Deal in deiner Stadt!</span>
                            </div>
                            <div class="item-content-link"><a href="#">Mehr...</a></div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-12 text-center">
                        <div class="item-img"><img src="/media/apps.png" alt=""></div>
                        <div class="item-info"><b>APPS & MOBILE</b></div>
                        <div class="item-content text-left">
                            <div class="item-content-text"><span>Bestell doch mal Essen bei einem Lieferservice mit der kengkeng.de App für iPhone, iPad, Android und Windows Phone oder über die mobile Website.</span>
                            </div>
                            <div class="item-content-link"><a href="#">Mehr...</a></div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-12 text-center" >
                        <div class="item-img"><img src="/media/livetracking.png" alt=""></div>
                        <div class="item-info"><b>KENGKENG.DE LIVETRACKING</b></div>
                        <div class="item-content text-left">
                            <div class="item-content-text"><span>Mit dem LiveTracking von kengkeng.de kannst du die Lieferung des Lieferdiensts in Echtzeit auf der Karte mitverfolgen.</span>
                            </div>
                            <div class="item-content-link"><a href="#">Mehr...</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container container-6">
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="content-6 content">
                <div class="content-title"><b>PIZZA LIEFERSERVICE UND PIZZASERVICE</b></div>
                <ul class="list-item ">
                    <?php $citys = $this->getAllCity();
                    foreach ($citys as $item) :?>
                        <li class="item col-xs-6 col-md-4"><a
                                    href="/admin_storelisting/index/list/?search=1&lng=<?php echo $item->getLongitude() ?>&lat=<?php echo $item->getLatitude() ?>"><?php echo $item->getCity() ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container container-4">
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="content-4 content">
                <div class="list-item">
                    <div class=" col-md-6 col-xs-12 text-center">
                        <div class="title"><b>ONLINE ESSEN BESTELLEN</b></div>
                        <div class="text text-left">Auf kengkeng.de bei den besten Lieferdiensten und Pizzaservices in ganz
                            Deutschland online Essen bestellen. Die Bestellung ist einfach, zuverlässig und kommt binnen
                            Sekunden beim gewählten Lieferservice an. Ob Pizza, Asiatisch, Sushi, Burger, Indisch oder
                            andere Fast-Food-Spezialitäten: Einfach passendes Gericht auswählen und direkt online
                            bestellen. Bezahlt werden Thai, Pasta und Gyros easy online mit PayPal, VISA oder
                            Sofortüberweisung oder wie gewohnt bei Lieferung.
                        </div>
                        <div class="link text-left"><a href="#">Mehr...</a></div>
                    </div>
                    <div class="col-md-6 col-xs-12 text-center">
                        <div class="title "><b>LIEFERDIENSTE FÜR JEDEN GESCHMACK</b></div>
                        <div class="text text-left">Auf kengkeng.de geht es um viel mehr als nur um Pizza. Egal, ob Chinesisch,
                            Burger, Döner, Salate oder Griechisch: Alle Köstlichkeiten der modernen Küche lassen sich
                            ganz einfach vom Bestellservice nach Hause liefern. Finde durch die Empfehlungen anderer
                            Besteller die besten Gerichte deiner Stadt. Oder verfolge mit dem kengkeng.de LiveTracking
                            die Lieferung deines Essens vom Restaurant bis an die Haustür!
                        </div>
                        <div class="link text-left"><a href="#">Mehr...</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container container-5">
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="col-md-4 col-xs-12">
                <div class="item-title text-center">
                    <b>SICHERHEIT</b>
                </div>
                <div class="item-content">
                    Der Schutz der Privatsphäre hat bei uns höchste Priorität. Wir handeln nicht mit Daten und
                    schützen sie durch technische Maßnahmen vor Missbrauch.
                </div>
                <div class="item-link">
                    <p><a href="#">Zuverlässigkeit
                        </a></p>
                    <p><a href="#">Verschlüsselung
                        </a></p>
                </div>
            </div>
            <div class="col-md-4 col-xs-12">
                <div class="item-title text-center">
                    <b>KENGKENG.DE AUF SOCIAL NETWORKS</b>
                </div>
                <div class="item-content clearfix">
                    <ul class="social-list">
                        <li class="social-item"><a href="#" target="_blank"><img src="/media/fb-social.jpg"
                                                                                 alt=""></a></li>
                        <li class="social-item"><a href="#" target="_blank"><img src="/media/gplus-social.jpg"
                                                                                 alt=""></a></li>
                        <li class="social-item"><a href="#" target="_blank"><img src="/media/tw-social.jpg"
                                                                                 alt=""></a></li>
                        <li class="social-item"><a href="#" target="_blank"><img src="/media/youtube-social.jpg"
                                                                                 alt=""></a></li>
                        <li class="social-item"><a href="#" target="_blank"><img src="/media/logo-social.jpg"
                                                                                 alt=""></a></li>
                    </ul>
                </div>
                <div class="item-link float-left">Hier erfährst du alles über unsere aktuellen Gewinnspiele, Aktionen und
                    Events.
                </div>
            </div>
            <div class="col-md-4 col-xs-12">
                <div class="item-title text-center">
                    <b>ÜBER KENGKENG.DE</b>
                </div>
                <div class="item-content">
                    <ul class="item-content-list">
                        <li class="col-xs-6"><a href="">testttttttttt</a></li>
                        <li class="col-xs-6"><a href="">testttttttttt</a></li>
                        <li class="col-xs-6"><a href="">testttttttttt</a></li>
                        <li class="col-xs-6"><a href="">testttttttttt</a></li>
                        <li class="col-xs-6"><a href="">testttttttttt</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>