<?php
//lấy danh sách các store từ block để hiển thị
?>
<!--<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">-->
<!--    <div class="form-group">-->
<!--        <label for="" class="col-sm-2 control-label"></label>-->
<!--        <div class="col-sm-6">-->
<!--            <select class="form-control" id="">-->
<!--                <option value="distance">--><?php //echo $this->__('Distance') ?><!--</option>-->
<!--                <option value="best">--><?php //echo $this->__('Best') ?><!--</option>-->
<!--                <option value="lowest">--><?php //echo $this->__('Lowest - Highest') ?><!--</option>-->
<!--                <option value="highest">--><?php //echo $this->__('Highest - Lowest') ?><!--</option>-->
<!--            </select>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

<div id="list-store">
<?php echo $this->getChildHtml('storelisting.index.list.store') ?>
</div>

<div class="modal" id="modal-review" style="display: none">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3><?php $this->__("Review Store") ?></h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>
<div class="loadding-img" style="display: none;">
    <img src="/media/storelisting/Loading_icon.gif" alt="">
</div>