<?php
//lấy danh sách các store từ block để hiển thị
$stores = $this->getStoreNearMe();
?>

<?php foreach ($stores as $store): ?>
    <div class="row">
        <div class="col-md-12">
            <div class="row restaurant">
                <div class="col-md-12">

                    <div class="border-box">
                        <div class="restaurant-detail">
                            <a href="<?php echo Mage::getUrl('storelisting/index/product', array('store_id' => $store['store_id']))?>" style="color: black">

                            <div class="col-md-2 col-xs-4 restaurant-detail-left">
                                <div class="restaurant-logo">
                                    <img  src="/media/storelisting/<?php echo $store['img'] ?>" alt=""></div>
                            </div>
                            </a>
                            <div class="col-md-10 col-xs-8 restaurant-detail-right">
                                <div class="row">
                                    <a href="<?php echo Mage::getUrl('storelisting/index/product', array('store_id' => $store['store_id']))?>" style="color: black">

                                    <div class="col-md-8 col-xs-12">
                                        <div class="restaurant-name"><h3><?php echo $store['namestore'] ?></h3></div>
                                        <div class="restaurant-address"><?php echo $store['address'] ?></div>
                                    </div>
                                    </a>
                                    <div class="col-md-4 col-xs-12">
                                        <div class="restaurant-item-start">
                                            <div class="count-review" data-store-id="<?php echo $store['store_id'] ?>"
                                                 style="cursor: pointer">
                                                (<?php echo $this->getCountReview($store['store_id']) ?>)
                                            </div>

                                            <div class="rating-box">
                                                <div class="rating" style="width: <?php echo $this->getRatingSummaryStore($store['store_id']) ?>%"></div>
                                            </div>

                                        </div>
                                        <!--                                                        <div class="restaurant-item-discount">-->
                                        <!--                                                            <div class="discount-badge">-->
                                        <!--                                                                <div class="badge">-->
                                        <!--                                                                    <div class="badge__content">-->
                                        <!--                                                                        <div class="badge__label"><span>15%</span></div>-->
                                        <!--                                                                        <div class="badge__message"><span>Deal</span></div>-->
                                        <!--                                                                    </div>-->
                                        <!--                                                                </div>-->
                                        <!--                                                            </div>-->
                                        <!--                                                        </div>-->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="restaurant-info">
                            <div class="col-md-4 col-xs-4">
                                <div class="restaurant-feature-cart-icon"><i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                </div>
                                <div class="restaurant-feature-cart-text"><span><?php echo $this->getLowestPriceProductStore($store['store_id']) ?> $</span></div>
                            </div>
                            <div class="col-md-4 col-xs-4">
                                <div class="restaurant-feature-cart-icon"><i class="fa fa-bicycle" aria-hidden="true"></i></div>
                                <div class="restaurant-feature-cart-text"><span><?php echo number_format((float)$store['distance'], 2, '.', ''); ?> KM</span></div>
                            </div>
                            <div class="col-md-4 col-xs-4">
                                <div class="restaurant-feature-cart-icon"><i class="fa fa-clock-o" aria-hidden="true"></i></div>
                                <div class="restaurant-feature-cart-text"><span><?php echo $store['time_open'] ?></span></div>

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>

    <!---->
    <!--            <li>-->
    <!--                <div class="panel panel-default" style="width: 250px;">-->
    <!--                    <div class="col-panel-left" style="width:40%;float: left">-->
    <!--                        <img src="--><?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?><!--\media\catalog\product\b\o\bonglan.jpg"-->
    <!--                             alt="">-->
    <!--                    </div>-->
    <!--                    <div class="col-panel-right" style="width:60%;float: left">-->
    <!--                        --><?php //echo $store['namestore'] ?>
    <!--                    </div>-->
    <!--                </div>-->
    <!---->
    <!--            </li>-->
    <!--        </a>-->

<?php endforeach; ?>

<div class="modal" id="modal" style="display: none">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Review Store</h3>
    </div>
    <div class="modal-body">

    </div>
    <div class="modal-footer">
    </div>
</div>
<div class="loadding-img" style="display: none;">
    <img src="/media/storelisting/Loading_icon.gif" alt="">
</div>